/*
file.out.js (c) 2023
Desc: description
Created:  2023-04-02T21:38:27.497Z
Modified: 2023-04-02T21:38:35.265Z
*/

async function clerkActions(e,a){"user_get_proxies"==a&&await getProxies(e)};async function loadClerk(){return new Promise(e=>{const a=document.createElement("script");a.setAttribute("data-clerk-frontend-api","clerk.a7i81.ec7ck.lcl.dev");a.async=!0;a.src="https://clerk.a7i81.ec7ck.lcl.dev/npm/@clerk/clerk-js@latest/dist/clerk.browser.js";a.addEventListener("load",async function(){await window.Clerk.load({});console.log("Clerk initiated \ud83d\udd12");clerkResolved()});document.body.appendChild(a);console.log("Clerk script loaded");setTimeout(()=>{e()},100)})}
const lsc=(e,a)=>new Promise((b,k)=>{const h=document.createElement("script");h.type="text/javascript";h.addEventListener("load",()=>{b({loaded:a+" loaded...",error:!1})});h.onerror=k;h.src=e;h.async=!1;document.body.append(h)});async function lscSupaClient(){await lsc("https://supa.illusory.io/storage/v1/object/public/js/supa/supaClient.js","supaClient.js").then(e=>console.log(e)).catch(e=>console.error(e.message))}
async function lscTimeAgo(){await lsc("https://cdnjs.cloudflare.com/ajax/libs/timeago.js/4.0.2/timeago.full.min.js","timeago.full.min.js").then(e=>console.log(e)).catch(e=>console.error(e.message))}
$("#cea_mod, #cea_nav").click(function(e){$(document).ready(function(){var a=document.getElementById(e.target.id),b=document.getElementById("prx_mod"),k=document.getElementById("nav_sb"),h=b.getAttribute("open"),l=k.getAttribute("open");if("cea_mod"==a.id){console.log(a.id);var d="true"==h?"false":"true";b.setAttribute("open",d)}else d="true"==h?"true":"false";if("cea_nav"==a.id){var f="true"==l?"false":"true";k.setAttribute("open",f)}else f="true"==l?"true":"false";"true"==f&&"false"==d&&(1800<=
$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr 1fr 1fr"}),$(".crds_col").css({width:"89%"}),$(".ind_wrp_v2").css({"margin-right":"3rem"})),1799>=$(window).width()&&1600<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr 1fr"}),$(".crds_col").css({width:"87%"}),$(".ind_wrp_v2").css({"margin-right":"3rem"})),1599>=$(window).width()&&1451<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr 1fr"}),$(".crds_col").css({width:"85%"}),$(".ind_wrp_v2").css({"margin-right":"3rem"})),
1450>=$(window).width()&&1281<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr"}),$(".crds_col").css({width:"84%"}),$(".ind_wrp_v2").css({"margin-right":"3rem"})),1280>=$(window).width()&&1081<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr"}),$(".crds_col").css({width:"81%"}),$(".ind_wrp_v2").css({"margin-right":"0"})),1080>=$(window).width()&&881<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr"}),$(".crds_col").css({width:"77%"}),
$(".ind_wrp_v2").css({"margin-right":"0"})),880>=$(window).width()&&680<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr"}),$(".crds_col").css({width:"70%"}),$(".ind_wrp_v2").css({"margin-right":"0"})));$(window).resize(function(){"true"==f&&"false"==d&&(1800<=$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr 1fr 1fr"}),$(".crds_col").css({width:"89%"}),$(".ind_wrp_v2").css({"margin-right":"3rem"})),1799>=$(window).width()&&1600<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr 1fr"}),
$(".crds_col").css({width:"87%"}),$(".ind_wrp_v2").css({"margin-right":"3rem"})),1599>=$(window).width()&&1451<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr 1fr"}),$(".crds_col").css({width:"85%"}),$(".ind_wrp_v2").css({"margin-right":"3rem"})),1450>=$(window).width()&&1281<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr"}),$(".crds_col").css({width:"84%"}),$(".ind_wrp_v2").css({"margin-right":"3rem"})),1280>=$(window).width()&&1081<$(window).width()&&
($(".cards-v2").css({"grid-template-columns":"1fr 1fr"}),$(".crds_col").css({width:"81%"}),$(".ind_wrp_v2").css({"margin-right":"0"})),1080>=$(window).width()&&881<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr 1fr"}),$(".crds_col").css({width:"77%"}),$(".ind_wrp_v2").css({"margin-right":"0"})),880>=$(window).width()&&680<$(window).width()&&($(".cards-v2").css({"grid-template-columns":"1fr"}),$(".crds_col").css({width:"70%"}),$(".ind_wrp_v2").css({"margin-right":"0"})))})})});
async function getProxies(e){const {data:a,error:b}=await e.from("proxies_restricted").select().order("proxy_name",{ascending:!0});return new Promise(k=>{setTimeout(()=>{if(b)console.error("we got an error:",b);else{const w=document.getElementsByClassName("cards-v2")[0];w.innerHTML="";for(var h=0,l=0;l<a.length;l++){var d=a[l],f=document.createElement("div");f.setAttribute("prx_card",d.proxy_name);f.classList.add("prx_crd_v2");f.setAttribute("onclick","interact(this)");f.setAttribute("interact",d.proxy_name);
w.appendChild(f);var c=document.createElement("div");c.classList.add("prx_crd_top");f.appendChild(c);f=document.createElement("div");f.classList.add("prx_crd_ti_v2");f.setAttribute("prx_res_timer",d.proxy_name);c.appendChild(f);f=document.createElement("div");f.classList.add("prx_crd_tit_sec_v2");f.classList.add("w-clearfix");c.appendChild(f);var g=document.createElement("div");g.classList.add("ico_rot_v2");g.classList.add("w-embed");f.appendChild(g);var n=new Image;n.src="https://assets.website-files.com/601983fb7d31a9e2fe9f0840/61aa903bc84f5b905f432b4f_rotate-cw.svg";
n.setAttribute("onclick","resetProxy(this.id)");n.setAttribute("id","reset_"+d.proxy_name);g.appendChild(n);g=document.createElement("div");g.classList.add("prx_crd_det_v2");f.appendChild(g);g=document.createElement("div");g.classList.add("crd_tit_v2");g.classList.add("smaller");g.innerHTML=d.proxy_name;g.setAttribute("crd_tit",d.proxy_name);f.appendChild(g);g=document.createElement("div");g.classList.add("prx_subtxt_v2");g.setAttribute("crd_ports",d.proxy_name);g.classList.add("smaller");g.innerHTML=
"HTTP "+d.h_port+" \u2022 SOCKS5 "+d.s_port;f.appendChild(g);f=document.createElement("div");f.classList.add("ind_wrp_v2");f.classList.add("w-clearfix");c.appendChild(f);if("AT&T"==d.isp)var u="blue";else"Verizon"==d.isp?u="red":"T-Mobile"==d.isp&&(u="pink");c=document.createElement("div");c.classList.add("ind_v3");c.classList.add(u);c.innerHTML=d.isp;c.setAttribute("crd_isp",d.proxy_name);f.appendChild(c);c=document.createElement("div");c.classList.add("ind_v3");c.classList.add("purple");c.innerHTML=
d.location;c.setAttribute("crd_loc",d.proxy_name);f.appendChild(c);c=document.createElement("div");c.classList.add("ind_v3");c.classList.add("light-blue");c.innerHTML=parseInt(d.h_threads)+parseInt(d.s_threads)+" threads";c.setAttribute("crd_threads",d.proxy_name);f.appendChild(c);if(1024>d.traffic)var p="Bytes",q=1;else 1024<=d.traffic&&1048576>d.traffic?(p="KB",q=1024):1048576<=d.traffic&&1073741824>d.traffic?(p="MB",q=1048576):1073741824<=d.traffic&&1099511627776>d.traffic?(p="GB",q=1073741824):
1099511627776<=d.traffic&&(p="TB",q=1099511627776);1024>d.traffic?(c=parseInt(d.traffic)/parseInt(q),c=c+" "+p):(c=parseInt(d.traffic)/parseInt(q),c=c.toFixed(2)+" "+p);g=document.createElement("div");g.classList.add("ind_v3");g.classList.add("light-blue");g.innerHTML=c;g.setAttribute("crd_traffic",d.proxy_name);f.appendChild(g);1==d.auto_change?(c="green",g="auto-change updating",n="auto_change_on"):(c="grey",g="auto-change off",n="auto_change_off");const r=document.createElement("div");r.classList.add("ind_v3");
r.classList.add(n);r.classList.add(c);r.innerHTML=g;r.setAttribute("crd_auto",d.proxy_name);r.setAttribute("datetime",d.next_ip_change);f.appendChild(r);c=document.createElement("div");c.classList.add("ind_v3");c.classList.add("last_ip_change");c.setAttribute("datetime",d.last_ip_change);c.innerHTML="ip change updating";c.setAttribute("crd_last_ip_change",d.proxy_name);f.appendChild(c);c=document.createElement("div");c.classList.add("ind_v3");c.classList.add("last_reboot");c.setAttribute("datetime",
d.last_reboot);c.innerHTML="reboot updating";c.setAttribute("crd_last_reboot",d.proxy_name);f.appendChild(c);document.getElementById("mod_x").setAttribute("onclick","closeModal(this)");h=parseInt(h)+1;document.querySelector("#all_isps_cnt").innerHTML=h}}k()},200)})}
async function rpcProxy(e){await e.channel("proxies_restricted").on("UPDATE",a=>{const b=a.new.proxy_name,k=a.new.auto_change,h=a.new.auto_change_time,l=a.new.h_port,d=a.new.h_threads,f=a.new.isp,c=a.new.last_ip_change,g=a.new.last_reboot,n=a.new.location,u=a.new.next_ip_change,p=a.new.password,q=a.new.s_port,w=a.new.s_threads,r=a.new.server_ip,m=a.new.traffic,x=a.new.username,y=a.new.whitelist;console.log(a);if(1024>m)var t="Bytes",v=1;else 1024<=m&&1048576>m?(t="KB",v=1024):1048576<=m&&1073741824>
m?(t="MB",v=1048576):1073741824<=m&&1099511627776>m?(t="GB",v=1073741824):1099511627776<=m&&(t="TB",v=1099511627776);1024>m?(a=parseInt(m)/parseInt(v),t=a+" "+t):(a=parseInt(m)/parseInt(v),t=a.toFixed(2)+" "+t);document.querySelector("[crd_ports="+b+"]").innerHTML="HTTP "+l+" \u2022 SOCKS5 "+q;document.querySelector("[crd_isp="+b+"]").innerHTML=f;document.querySelector("[crd_loc="+b+"]").innerHTML=n;document.querySelector("[crd_threads="+b+"]").innerHTML=parseInt(d)+parseInt(w)+" threads";document.querySelector("[crd_traffic="+
b+"]").innerHTML=t;1==k?(document.querySelector("[crd_auto="+b+"]").classList.remove("grey"),document.querySelector("[crd_auto="+b+"]").classList.remove("auto_change_off"),document.querySelector("[crd_auto="+b+"]").classList.add("green"),document.querySelector("[crd_auto="+b+"]").classList.add("auto_change_on"),document.querySelector("[crd_auto="+b+"]").innerHTML="auto-change updating",document.querySelector("[crd_auto="+b+"]").setAttribute("datetime",u)):(timeago.cancel(document.querySelector("[crd_auto="+
b+"]")),document.querySelector("[crd_auto="+b+"]").classList.remove("green"),document.querySelector("[crd_auto="+b+"]").classList.remove("auto_change_on"),document.querySelector("[crd_auto="+b+"]").classList.add("grey"),document.querySelector("[crd_auto="+b+"]").classList.add("auto_change_off"),document.querySelector("[crd_auto="+b+"]").innerHTML="auto-change off",document.querySelector("[crd_auto="+b+"]").setAttribute("datetime",""));document.querySelector("[crd_last_ip_change="+b+"]").setAttribute("datetime",
c);document.querySelector("[crd_last_reboot="+b+"]").setAttribute("datetime",g);(new URLSearchParams(window.location.search)).get("proxy")==b&&($("#currentProxy").html(b),$("#cp-autoMinOnly").val(h),$("#cp-isp").html(f),$("#cp-loc").html(n),$("#cp-threads").html(w+d+" Threads"),$("#cp-traffic").html(m),$("#cp-lastReset").attr("datetime",c),$("#cp-lastReboot").attr("datetime",g),$("#uname").html(x),$("#pword").html(p),$("#unameInput").val(x),$("#pwordInput").val(p),$("#whitelistIp").val(y),$("#serverIp").html(r),
$("#httpPort").html(l),$("#socksPort").html(q),timeago.cancel(document.getElementById("cp-lastReset")),timeago.cancel(document.getElementById("cp-lastReboot")),async function(){await modal_time_ago()}());(async function(){await getTimeAgoManual();await getTimeAgoReboot();1==k&&await getTimeAgoAuto()})()}).subscribe()}
async function interact(e){await openModal();$(".prx_crd_v2").css({border:"1px solid #111314","background-color":"#080909",transition:".1s"});$(e).css({border:"#6dffa8 0.15rem solid","background-color":"#141517",transition:".1s"});var a=e.getAttribute("interact");const {data:b,error:k}=await supabaseClient.from("proxies_restricted").select().eq("proxy_name",a);return new Promise(h=>{if(k)$("#successMsg").hide(),$("#errorMsg").hide(),$("#errorMsg").show(),$("#errorTxt").html(k.response.data.message),
console.error(k);else{window.localStorage.setItem("currentProxy",a);document.title=a;var l=new URLSearchParams(window.location.search);l.set("proxy",a);history.replaceState(null,null,"?"+l.toString());l=b[0].online;var d=b[0].username,f=b[0].password,c=b[0].server_ip,g=b[0].h_port,n=b[0].s_port,u=b[0].whitelist,p=b[0].last_ip_change,q=b[0].last_reboot,w=b[0].s_threads,r=b[0].h_threads,m=b[0].location,x=b[0].isp,y=b[0].traffic,t=b[0].auto_change,v=b[0].auto_change_time,z=b[0].auth_method;$("#currentProxy").html(a);
$("#cp-autoMinOnly").val(v);$("#cp-isp").html(x);$("#cp-loc").html(m);$("#cp-threads").html(w+r+" Threads");$("#cp-traffic").html(y);$("#cp-lastReset").html(p);$("#cp-lastReboot").html(q);$("#cp-lastReset").attr("datetime",p);$("#cp-lastReboot").attr("datetime",q);$("#uname").html(d);$("#pword").html(f);$("#unameInput").val(d);$("#pwordInput").val(f);$("#whitelistIp").val(u);$("#serverIp").html(c);$("#httpPort").html(g);$("#socksPort").html(n);1==l?($("#cp-online").show(),$("#cp-offline").hide()):
($("#cp-online").hide(),$("#cp-offline").show());"creds"==z?($("#userPassSel").click(),$("#authMethodConf").html("Username & Password Selected")):($("#whitelistIpSel").click(),$("#authMethodConf").html("Whitelist IP Selected"));null==d?($("#userPassSelNone").show(),$("#userPassSelSet").hide()):($("#userPassSelNone").hide(),$("#userPassSelSet").show());null==u?($("#whitelistSelNone").show(),$("#whitelistSelSet").hide()):($("#whitelistSelNone").hide(),$("#whitelistSelSet").show());1==t?($("#autoChangeOn").css("display",
"flex"),$("#autoChangeOnLine, #autoChangeOnRow").show(),$("#autoChangeOff").hide()):($("#autoChangeOff").css("display","flex"),$("#autoChangeOn, #autoChangeOnLine, #autoChangeOnRow").hide());$("#auth_options").hide();(async function(){await modal_time_ago();await hide_skel_mod()})()}setTimeout(()=>{h("Got modal details...")},100)})}async function modalStart(){return new Promise(e=>{document.getElementById("prx_mod").setAttribute("open",!1);setTimeout(()=>{e("Set open: false.")},100)})}
async function openModal(){await show_skel_mod();return new Promise(e=>{$("#prx_mod").css("display","flex");$(".crd_wrp").hide();document.getElementById("prx_mod").setAttribute("open",!0);setTimeout(()=>{e("Opened")},100)})}async function closeModal(){return new Promise(e=>{const a=document.getElementById("prx_mod");$("#prx_mod").hide();$(".crd_wrp").show();$(".auth-select-wrap").hide();$(".webhook-online-trigger-wrap").hide();a.setAttribute("open",!1);setTimeout(()=>{e("Closed")},100)})}
$(".add_min").click(function(){1440>$(this).prev().val()&&$(this).prev().val(+$(this).prev().val()+1)});$(".sub_min").click(function(){1<$(this).next().val()&&1<$(this).next().val()&&$(this).next().val(+$(this).next().val()-1)});async function navStart(){return new Promise(e=>{setTimeout(()=>{document.getElementById("nav_sb").setAttribute("open",!0);e("Set open: true.")},100)})}
async function openNav(){await show_skel_mod();return new Promise(e=>{setTimeout(()=>{document.getElementById("nav_sb").setAttribute("open",!0);e("Opened")},100)})}async function hide_skel_dash(){return new Promise(e=>{setTimeout(()=>{$(".crd_wrp").show();$(".skel_cnt_active").hide();$(".crd_skel_wrp").hide();e("Hid card skeletons")},100)})}
async function hide_skel_mod(){return new Promise(e=>{setTimeout(()=>{document.querySelectorAll(".skel_mod").forEach(function(a){a.style.display="none"});document.querySelectorAll(".skel_light").forEach(function(a){a.style.display="none"});e("Hid mod skeletons")},100)})}
async function show_skel_mod(){return new Promise(e=>{setTimeout(()=>{document.querySelectorAll(".skel_mod").forEach(function(a){a.style.display="block"});document.querySelectorAll(".skel_light").forEach(function(a){a.style.display="block"});e("Unhid mod skeletons")},100)})}function iniIx2(){return new Promise(e=>{setTimeout(()=>{$(document).ready(function(){window.Webflow&&window.Webflow.require("ix2").init();document.dispatchEvent(new CustomEvent("IX2_PREVIEW_LOAD"))});e()},500)})}$("#change_ip_mod").click(function(){change_ip()});
async function change_ip(){var e=localStorage.getItem("currentProxy");await supabaseClient.auth.getUser();let {data:a,error:b}=await supabaseClient.rpc("dash_func_change_ip_v3",{name_input:e,change_ip_input:!0,origin_input:"dashboard"});b?console.error(b):console.log(a)}$("#reboot_mod").click(function(){reboot_device()});
async function reboot_device(){var e=localStorage.getItem("currentProxy"),{data:{user:a}}=await supabaseClient.auth.getUser();let {data:b,error:k}=await supabaseClient.rpc("dash_func_reboot_v1",{name_input:e,reboot_input:!0,email_input:a.email,origin_input:"dashboard"});k?console.error(k):console.log(b)}async function pageInit(){await lscSupaClient();await loadClerk()}
async function clerkResolved(){const e=await supaClient();await clerkActions(e,"user_get_proxies");await lscRpcProxy();await lscTimeAgo();await navStart();await modalStart();await iniIx2();await hide_skel_dash()}pageInit();